### ISSUE TITLE
When first visiting page login always fails

### ISSUE THREAD

**Issue by jesshmusic** [mzenzie/320MusicLessonPlanner#41]
After trying to login after first visiting the page the login will fail regardless of whether or not it is entered correctly. (Seems to be a UI-Router implementation issue).
To recreate bug:
Type: http://localhost:8000 in the browser and press Enter.

**Comment by nsimsiri** [comment]
Must use an the JwtInterceptor. Fixed by uncommenting jwt code in Config.js
JwtInterceptorProvider is an Interceptor - you can google angular inceptor for more details.
What this JwtInterceptor does is for every request we make, we are appending to the header the field
"Authorization: Bearer <token> "
so that the Server can verify this User and give permission to protected API if neccesary. 
- JwtInterceptor is an Interceptor - see: https://docs.angularjs.org/api/ng/service/$http - Interceptor section
- RFC on passing tokens via HTTP: https://tools.ietf.org/html/rfc6750

**Comment by jesshmusic** [comment]
That code was _not_ commented in my code. When I specifically type localhost:8000 in my browser (_not_ just reloading) login still fails.

**Comment by jesshmusic** [comment]
This is apparently related to the '?' in the url, and seems to affect browsers differently.
Login works as intended with the '?' in Safari, but _not_ in Firefox. See issue #52.

**Comment by jesshmusic** [comment]
This issue has apparently resolved itself, as I have not had this problem on Safari, Firefox, or Chrome. The '?' is gone from all URLs.
I assume that bcrypt update fixed it?
